typelevel/cats-parse

- .github/workflows/ci.yml
- .gitignore
- project/plugins.sbt
Fixes https://github.com/typelevel/cats-parse/issues/25 to remove the use of deprecated methods in github actions by upgrading to 0.9.4.
> Upgrading sbt-github-actions to 0.9.4 to remove deprecations

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
I had naively hoped a strong distributive law would hold. This cannot hold for parsers without total backtracking and as such seems like it was perhaps erroneously added to cats Alternative law testing. I added a comment linking to some past difficulties cats had with a related issue and also to a discussion that some Haskell Alternative instances are not distributive.
cc @non
> Test some distributivity laws

- core/shared/src/main/scala/cats/parse/Parser.scala
I'm trying to work through and write more descriptive Scaladoc comments.
In particular, I've coined the term _arresting failure_ to contrast with _epsilon failure_. I think this makes a lot of the prose easier to follow.
What do you think? cc @johnynek @rossabaker
> First pass at improving the Scaladoc comments.

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This was an oversight in the originally released code.
The use case is to allow validation by users especially when used with flatMap.
> Add failWith for user defined error messages

- core/shared/src/main/scala/cats/parse/Accumulator.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
I chatted with this idea with @non after seeing an example CSV parser he wrote and seeing where it could have come in handy.
> Add ability to repeat into different structures

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
Some grammars, like SQL, unfortunately need case-insensitive token matching. This adds this functionality.
> Case-insensitive string parsers

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
follow up to #46 
What do you think @stephenjudkins ? I want to publish a new version, but the name just wasn't sitting well with me.
Can you review this and the other new methods I added?
There is one ambiguity: string can be converted to `Iterable[Char]` in scala, so I added `ignoreCaseChar` and `ignoreCaseCharIn` but to save space for the common case, I used ignoreCase to accept a string. A clearer, but more verbose approach would be to do ignoreCaseString, but I feel that's a bit long. That said, ignoring case isn't that common, so maybe that's okay. I don't know.
> Add some ignoreCase methods, rename stringCI to ignoreCase

- PULL_REQUEST_TEMPLATE.md
- build.sbt
This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.
> Thank you for contributing to `cats-parse`!

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
I looked at the code on in the java standard library, and by calling regionMatches with a boolean, we have to do another branch inside that code to go to the non-ignore-case mode.
We already have many subclasses of Parser, so by adding one more we aren't harming the optimizer. So, this PR makes a separate case class for ignoring the case, in this way, users that don't ignore the case don't hit a different code path. String parsing is fairly important to the benchmarks, so this seems to give a few % improvement.
Also, I added ignoreCase to the generators to get better coverage.
benchmarks before:
```
[info] Benchmark                        Mode  Cnt    Score    Error  Units
[info] BarBench.catsParseParse          avgt   10   ≈ 10⁻⁴           ms/op
[info] BarBench.fastparseParse …
```
> Improve performance around ignoreCase

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
A few more laws occurred to me so I added them.
At the same time, I realized we could leverage some of those properties when statically building up the parsers to make them a bit simpler.
> Add a few new laws and optimizations

- core/shared/src/main/scala/cats/parse/Parser.scala
before:
```
[info] Benchmark                           Mode  Cnt    Score    Error  Units
[info] BarBench.catsParseParse             avgt    3   ≈ 10⁻³           ms/op
[info] Bla25Bench.catsParseParse           avgt    3   42.306 ±  6.775  ms/op
[info] CountriesBench.catsParseParse       avgt    3   16.722 ±  4.179  ms/op
[info] Qux2Bench.catsParseParse            avgt    3   13.183 ±  1.485  ms/op
[info] Ugh10kBench.catsParseParse          avgt    3  100.625 ± 27.054  ms/op
```
after:
```
[info] Benchmark                           Mode  Cnt   Score    Error  Units
[info] BarBench.catsParseParse             avgt    3  ≈ 10⁻⁴           ms/op
[info] Bla25Bench.catsParseParse           avgt    3  35.326 ±  8.988  ms/op
[info] CountriesBench.catsParseParse       avgt    3  14.109 ±  3.304 …
```
> Small optimization around makeError

- core/js/src/main/scala/cats/parse/BitSet.scala
- core/jvm/src/main/scala/cats/parse/BitSet.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
related to #64 here are some special cases to make sure we don't harm efficiency when converting between original, string, and void return types.
cc @rossabaker
> Optimize string, void and char cases a bit

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This idea is that in unmap, we can right associate without any additional cost, so why not.
This means if the first item in a product does not match, we can see that quickly. Since unmap is used by void and string, both very common, this should be a meaningful optimization.
Here are benchmarks of this PR:
```
[info] Benchmark                        Mode  Cnt    Score    Error  Units
[info] BarBench.catsParseParse          avgt    5    0.001 ±  0.001  ms/op
[info] BarBench.fastparseParse          avgt    5   ≈ 10⁻⁴           ms/op
[info] BarBench.jawnParse               avgt    5   ≈ 10⁻⁴           ms/op
[info] BarBench.parboiled2Parse         avgt    5   ≈ 10⁻⁴           ms/op
[info] BarBench.parsleyParseCold        avgt    5    0.154 ±  0.004  ms/op
[info] Bla25Bench.catsParseParse …
```
> Right associate products in unmap

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This increases the test coverage of the recent #79 PR.
Also, a minor improvement of unmap for right association #82 - we use Void which acts as a signal that something is already unmapped.
> Increase test coverage a bit

- .github/workflows/ci.yml
- bench/src/main/scala/cats/parse/bench/atto.scala
- bench/src/main/scala/cats/parse/bench/fastparse.scala
- bench/src/main/scala/cats/parse/bench/parboiled2.scala
- bench/src/main/scala/cats/parse/bench/parsley.scala
- bench/src/main/scala/cats/parse/bench/self.scala
- build.sbt
With this we propagate `compile` and `fmt` tasks/commands.
> Aggregate bench project

- build.sbt
- core/shared/src/main/scala/cats/parse/Parser.scala
This was an oversight: the repAs1 extension method hid that it returns a Parser1
The work around is to directly call the repAs1 method on the Parser companion which does return the correct type.
> Fix return type on repAs1

- core/shared/src/main/scala/cats/parse/LocationMap.scala
- core/shared/src/test/scala/cats/parse/LocationMapTest.scala
This adds some code from bosatsu which converts offsets in the string into lines and columns.
This is intended for users to convert offsets in errors into snippets to display to the user (by combining toLineCol with getLine).
@rossabaker I'd love your review here.
In bosatsu, I have a bit more, a function to show the context and to point to the offset, but it uses paiges Doc, and I don't want to add that dependency at this time.
I thought a bit about how to abstract that out, but it isn't trivial. I figured this part is at least part of what we want.
> Add LocationMap to help users show error locations

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
Riffing on the ideas of [Staged Selective Parser Combinators](https://mpickering.github.io/papers/parsley-icfp.pdf).
Use case: in http4s, we need to parse various date headers into a 7-tuple of (weekday, year, month, day, hour, minute, second), and then verify that the date is valid (e.g., no 31st of February).  Currently we have to flatMap it, and when parsing, we _don't_ want to flatMap that shit.
Implemented on `branch`.  We should have the full power of Selective.  The primitive operation could also be `select`, which is the abstract function on cats-selective.
Should be able to make a version that fails with a particular message, swapping that in for "empty".
There may be optimizations to sprinkle throughout the code.  Fusing to `Impl.Map` seems possible, for instance.
I'm super …
> filter, based on selective

- core/shared/src/test/scala/cats/parse/ParserTest.scala
This is a law that shows the when first argument of the select is Right, we don't look at the second parser.
> Add a simple law for select

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This does a few things:
1. add an arbitrary for Parser that just maps a totally general one into the right type. This should make those parser internally complex, but have the right type for some simple law writing
2. add a few new laws that are easier to write, or that were overlooked in the past
3. add FunctorFilter methods which are related to filter, but also allows a transformation at the same time, e.g. convert a string to an Int32: usually it is easy to see if a string contains a big integer, but only parsing valid int32 makes a very complex parser and potentially bad error messages (although, using a failWith to explain is probably better here, but that pushes you out of select and into flatMap territory).
what do you think @rossabaker
> Implement FunctorFilter and add some more laws

- core/shared/src/main/scala/cats/parse/Parser.scala
Just noticed that for `string` it unmap'ing 2 times. not sure if I'm missing anything.
> Fix string unmap with Parser1

- bench/src/main/scala/cats/parse/bench/self.scala
- build.sbt
- core/shared/src/main/scala/cats/parse/Accumulator.scala
- core/shared/src/main/scala/cats/parse/Numbers.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/main/scala/cats/parse/Rfc5234.scala
- core/shared/src/main/scala/cats/parse/SemVer.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- core/shared/src/test/scala/cats/parse/Rfc5234Test.scala
- docs/src/index.md
To illustrate https://github.com/typelevel/cats-parse/issues/113
Moved the constructors and their helper wrappers to `object Parser` (in the easiest way possible, by loosening access), in the second to last commit, and taking things to their logical extreme in I removed `parse` and `parseAll` from `Parser0`: it makes little sense to run an end-parser on a string that may not consume any characters, 
That the intuition works out is shown in that none of the "real world" tests needed changing other than catching that some `Parser(1)`'s could be `Parser0`'s.
Todo: Fixup the fallout of submitting too early while by while writing up the body of the PR and still running tests.
> Make 1 the default: rename Foo1 things to Foo, and the associated Foo to Foo0

- bench/src/main/scala/cats/parse/bench/self.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This is a minor change after #116
1. as discussed, with make orElse name the same. I was reluctant since I was nervous that scala wouldn't find the right method, but I guess it works fine.
2. a few name changes (Map1 becomes Map).
3. a couple minor optimizations (repAs in rep(min: Int), optimize `.as(foo).map(fn)` to be `.as(foo(fn))` to avoid evaluating fn on each value.
4. Make Impl private again, lift State out and make just that `private[parse]`. I prefer to use the stronger encapsulation (private) if we can.
What do you think @martijnhoekstra @regadas
> Some minor nits post Parser0 change

- .gitignore
- bench/src/main/scala/cats/parse/bench/self.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- core/shared/src/test/scala/cats/parse/RepParserConstructionTest.scala
- docs/src/index.md
relates to #137 
This does a few things to make the API more consistent:
1. rename rep0Sep to repSep0. All the other methods with 0, such as repAs0, end in 0, this was the only one in the middle.
2. add a repSep variant with a maximum.
3. a few internal nits (use repExactly if possible, if repExactly is times = 1, just use map).
cc @regadas @martijnhoekstra
> Some more pre-0.3.0 changes

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/main/scala/cats/parse/SemVer.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
Closes #111 
The minimal implementation: does not include other possible extensions of repSep like repSepAs with accumulator or repSep with trailing separator.
> RepSep overload with no `min` parameter

- core/shared/src/main/scala/cats/parse/SemVer.scala
It's unused and there is no reason why you should use SemVer.positiveDigit over Numbers.nonZeroDigit
Could perhaps still go along with 0.3.0 in the hopes nobody uses it, and never will? Or deprecate first?
> remove nonNegativeDigit in SemVer

- core/shared/src/test/scala/cats/parse/ParserTest.scala
These tests were failing if the input strings were repeating, and the part before the ~ matched the first half.
> fix tests: use whole prefix length in case of repeating strings

- core/shared/src/main/scala/cats/parse/Parser.scala
Originally the `ParserMethods` class was intended to avoid writing a type like:
```scala
def repAs[A1 >: A, B](implicit acc: Accumulator[A1, B]): Parser[B]
```
But that is not needed because `Accumulator` and `Accumulator0` are contra variant in the first type parameter. Thus, we can put them as regular methods on `Parser[A]` without any ugly signatures and still be able to write `p.repAs[NonEmptyVector[Int]]` without having to name the input type (`Int` in this example).
This should be source compatible since we just moved implicit enrichments directly onto the class.
cc @martijnhoekstra @regadas
> Remove ParserMethods which is unneeded

- docs/src/index.md
Hi,
I just thought it might be useful to bump the versions in the README to the latest release version (0.3.1). `0.2.0` doesn't support Dotty so its inconsistent with the rest of the doc.
> Update versions in README

- .github/workflows/ci.yml
- build.sbt
- project/Dependencies.scala
Helping with https://github.com/http4s/http4s/pull/4681
> Out with 3.0.0-M3, in with Scala 3.0.0-RC2

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
close #43 
This follows the design sketched in the issue above. The goals are:
1. not break compatibility
2. not add a performance tax on those not using the feature
3. enable users to add strings to track where they are in a parser.
cc @kubukoz @mpilquist
> Add withContext to improve error reporting

- build.sbt
> Fix sbt 1.5.1 deprecated scoping

- .github/workflows/ci.yml
- build.sbt
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- project/Dependencies.scala
There a couple of minor costs here:
1. we lose an override of filterFunctor, but honestly we should send a PR to cats because the default implementation seems like it could be improved.
2. we lose an override of Defer.fix, which I doubt is very important.
3. We do not support scalajs on 2.11 since that's cutting really fine: there are a very small number of folks who want an old scala version AND scala js.
> Support 2.11.12 by using old cats

- docs/src/index.md
This pr is trying to fix https://github.com/typelevel/cats-parse/issues/272.
Currently the example in the readme can not actually work very well
> Fix json parse example

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- docs/src/index.md
address the kinds of errors seen here:
https://github.com/typelevel/cats-parse/issues/272#issuecomment-932541128
> Add .soft.between and .soft.surroundedBy

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
> Add soft.with1.between and surroundedBy

- core/shared/src/main/scala/cats/parse/LocationMap.scala
- core/shared/src/test/scala/cats/parse/LocationMapTest.scala
address the issue here:
https://github.com/typelevel/cats-parse/issues/239#issuecomment-860196982
cc @re-xyr @alissa-tung please take a look at review if you have time.
> Make LocationMap return a line/col on EOF

- core/js/src/main/scala/cats/parse/BitSet.scala
- core/jvm/src/main/scala/cats/parse/BitSet.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
1. If we have a single CharIn parser, we don't need to compute the union, just reuse it (which also saves recomputing the range of characters)
2. return a Set in the union function, not a List, which can return a large list if you have duplicates in your set.
> Improve merging of Char parsers

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This adds a law (that actually already passed), and makes unmap a bit more precise in the case of Defer.
> Make sure void is idempotent

- .gitignore
- docs/src/index.md
> Add tutorial to readme

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
close #263 
I made sure all the previous failures are no longer failures.
This fixes in a couple of ways:
1. add some of the static optimizations that we hit on some, but not all code paths
2. change some of the laws to relax them somewhat (mostly around overly strict equivalences in error cases)
This should be performance neutral or possibly slightly faster.
> Fix issue 263

- build.sbt
- core/shared/src/main/scala/cats/parse/Parser.scala
By putting the call to `makeError` inside `Eval.later` we can avoid the mima exclusion, which simplifies the build.
This is in preparation for publishing a new version hopefully today.
> Remove mima exclusion

- core/shared/src/main/scala/cats/parse/Caret.scala
- core/shared/src/main/scala/cats/parse/LocationMap.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/LocationMapTest.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
This does the caret part of #238 
related to #234 
I did not add Span, just Caret.
My concern was that the span methods are a bit less clear. For instance, we may want an inclusive upper bound range, or maybe we do want exclusive. Inclusive is a bit more complex to implement however.
To sidestep this concern for now while we think about the design, I just added getting the `Caret` itself.
cc @re-xyr
> Add Parser.caret

- core/shared/src/main/scala/cats/parse/Caret.scala
- core/shared/src/main/scala/cats/parse/LocationMap.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
I realized we used `line` instead of `row` in the `LocationMap` and we had a doc error that caused `v0.3.5` publish to fail, so I figured I could fix that.
> Fix some minor issues before 0.3.5

- core/shared/src/main/scala/cats/parse/LocationMap.scala
- core/shared/src/test/scala/cats/parse/LocationMapTest.scala
`line` was filled with `offset`, `col` was filled with `line` and `offset` with `col`.
I'm guessing at one point Caret was `Caret(offset, line, column)`, but was changed to `Caret(line, column, offset)` without re-examing argument order.
This caused this behavior:
```scala
val p = (Parser.caret.with1 <* Parser.anyChar).rep
val pattern = """aaa"""
val parsed = p.parseAll(pattern).right.get
// parsed: cats.data.NonEmptyList[Caret] = NonEmptyList(Caret(0, 0, 0), List(Caret(1, 0, 1), Caret(2, 0, 2)))
```
Expected:
```scala
// parsed: cats.data.NonEmptyList[Caret] = NonEmptyList(Caret(0, 0, 0), List(Caret(0, 1, 1), Caret(0, 2, 2)))
```
> fix Caret arguments ordering

- core/shared/src/main/scala/cats/parse/Caret.scala
- core/shared/src/test/scala/cats/parse/BitSetTest.scala
- core/shared/src/test/scala/cats/parse/LocationMapTest.scala
- docs/src/index.md
Does a few things:
1. bump the version mentioned in the readme
2. increase the number of test runs for LocationMapTest (which still doesn't it make it run more than a couple of seconds)
3. add a test that the pattern match on Caret is a certain order (the same order as comparison)
4. explain in a comment why the comparison order is what it is (in case we are comparing Carets from two different strings).
> Bump Readme versions and add some tests

- .scalafmt.conf
- build.sbt
- core/shared/src/main/scala-2/cats/parse/StringInterpolation.scala
- core/shared/src/main/scala-3/cats/parse/StringInterpolation.scala
- core/shared/src/test/scala/cats/parse/StringInterpolatorTest.scala
Fixes https://github.com/typelevel/cats-parse/issues/329.
I just dragged this over the finish line and am open to any suggested changes. Was a useful if somewhat painful way to dip my toes into Scala 3
> String interpolator parsers

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
People sometimes write .as(()) and this makes sure that is exactly the same as .void.
> Optimize .as(()) to .void

- bench/src/main/scala/cats/parse/bench/StringInBench.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/main/scala/cats/parse/RadixNode.scala
- core/shared/src/test/scala/cats/parse/RadixNodeTest.scala
part of #350 
This may be marginally faster, but the main value it adds is that RadixNode can now return the matching string without allocating. Also, I think the implementation is somewhat simpler.
I expect this should be faster if the set of strings gets larger (the benchmarks only have a few different prefixes. This uses a hash based approach so it is always O(1) to check a character (not log(N) worst case).
```
Before:
[info] Benchmark                         Mode  Cnt   Score   Error  Units
[info] StringInBenchmarks.linearMatchIn  avgt    3  77.603 ± 0.529  ns/op
[info] StringInBenchmarks.radixMatchIn   avgt    3  59.675 ± 2.126  ns/op
This PR:
[info] Benchmark                         Mode  Cnt   Score   Error  Units
[info] StringInBenchmarks.linearMatchIn  avgt    3  77.427 ± 4.083 …
```
> Improve RadixNode add a few more benchmarks

- .scalafmt.conf
It's ok to use it and for metals users, it will avoid the nagging.
> Use scalafmt scala213 runner dialect

- core/shared/src/main/scala/cats/parse/RadixNode.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- core/shared/src/test/scala/cats/parse/RadixNodeTest.scala
followup to #352 to fix an issue only noticed on second review.
Added a test on Parser first that failed, then fixed the bug.
> Fix RadixNode.matchAt

- core/shared/src/main/scala/cats/parse/Parser.scala
We use `Eval` to defer doing any work except allocation on errors since `oneOf` can recover failures. So we don't actually want to run the error condition until the end.
`Not` was allocating a copy of a string before the `Eval` so that allocation had to happen on every failure, which could be a lot for some cases. By moving the allocation inside the Eval we will (almost certainly) save.
> Optimize Not error condition

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
These are pretty useful and save the user from using `apply` on a Map which may appear unsafe to a reviewer in user code, but is safe in this context (we know we return a matching key).
> Add fromCharMap and fromStringMap

- core/shared/src/main/scala/cats/parse/Numbers.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
Previously we were using scalacheck `Arbitrary.arbitrary[String]` which generates strings from a huge space. The problem is that the chance you randomly generate anything that will parse will be very low.
Here we improve is somewhat by choosing strings from three spaces: `('a', 'A', 'b', 'B', ' ')`, printable ascii, and all unicode.
The idea is that some laws that might not fail for all unicode (because we just generate parsers and strings that never match) might fail if we restrict the string space enough.
No tests failed, but still I think it is better.
> Improve String generation

- core/shared/src/main/scala/cats/parse/Parser.scala
We were potentially hiding a `OneOf` by not carefully checking if each argument might be a `Parser`.
> minor improvement to cheapOneOf0

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- project/MimaExclusionRules.scala
give rep0/repAs0 the same treatment as #389
> Improve error reporting for rep0, repAs0

- .github/workflows/ci.yml
- build.sbt
Fixing the current `main` build issue introduced with https://github.com/typelevel/cats-parse/runs/6804145548
Including a Java step here as well since parboiled, dependency from paradox, is java 11 only now.
We had this before, but we can change CI to use Java 11 by default since we are setting the targets correctly.
> Only publish site on release

- .github/workflows/ci.yml
- build.sbt
- core/native/src/main/scala/cats/parse/BitSet.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
- core/shared/src/test/scala/cats/parse/RadixNodeTest.scala
- project/Dependencies.scala
- project/plugins.sbt
Squashes https://github.com/typelevel/cats-parse/pull/376 and brings it across the finish line.
> Cross-build for Native

- build.sbt
- core/jvm/src/test/scala/cats/parse/JvmNumbersTests.scala
- core/shared/src/test/scala/cats/parse/NumbersTest.scala
- project/Dependencies.scala
The idea here is to make sure we actually agree with a json number parsing implementation such as Jawn.
We should do the same for json string parsing when that is added #433
> Test json number parsing against Jawn

- core/shared/src/main/scala/cats/parse/Parser.scala
- core/shared/src/test/scala/cats/parse/ParserTest.scala
> Add withString

- core/shared/src/main/scala/cats/parse/Parser.scala
The comment for the `recursive` parser has a spelling error and its grammar could be improved. This is a very simple pull request that addresses these things!
---
> clean up 'recursive' parser description

- core/shared/src/main/scala/cats/parse/Accumulator.scala
- core/shared/src/main/scala/cats/parse/Parser.scala
prepare Scala 2.13.12
- https://github.com/scala/scala/pull/10439
> add explicit type

- docs/index.md
Update the README file to include the current latest cats-parse version `0.3.9` in `libraryDependencies`
> updates cats-parse version in libraryDependencies in README

- build.sbt
Since cats-parse is ready for a v1.0.0 release 🎉 
CI will continue enforcing bincompat with the entire 0.3.x series. Thus, the v1.0.0 release will simply be a "rebranding" and is not a breaking release.
cc @milessabin
> Bump base version to 1.0

- build.sbt
`tlReplaceCommandAlias` is deprecated. Use `tlCommandAlias` instead.
> Use tlCommandAlias for command aliases

- docs/index.md
> Typo fixed in index.md

- build.sbt
- core/jvm/src/test/scala/cats/parse/JvmNumbersTests.scala
- project/Dependencies.scala
- project/plugins.sbt
This PR adds support for Scala Native 0.5
In doing so it updates:
- scala to 2.13.14
- cats to 2.12.0
- scala-native to 0.5.4
- munit to 1.0.0
All of those changes may not have been strictly necessary, but it's what came naturally.
In particular, I'd love to have eyes on the [tlVersionIntroduced changes for Scala Native 0.5](https://github.com/typelevel/cats-parse/commit/05016138e40d8e5c759ecfea99c7fcd36e7797eb) 
resolves https://github.com/typelevel/cats-parse/pull/593
resolves https://github.com/typelevel/cats-parse/pull/589
resolves https://github.com/typelevel/cats-parse/pull/584
resolves https://github.com/typelevel/cats-parse/pull/574
> Support Scala native 0.5, Update deps

- docs/index.md
Current there is duplication / noise in the mdoc output from hardcoded result comments:
This PR removes these comments as mdoc computes and displays them for us.
> Reduce tutorial mdoc noise

- core/shared/src/main/scala/cats/parse/Parser.scala
> Implicitly use Show[Expectation]
