core/shared/src/test/scala/cats/parse/ParserTest.scala

this is a law that @non suggested.

Add a law relating backtrack and orElse

---

core/shared/src/main/scala/cats/parse/Parser.scala

Fixes nit in https://github.com/typelevel/cats-parse/pull/46

minor refactor in `stringCI1`

---

PULL_REQUEST_TEMPLATE.md
build.sbt

Closes #29
This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.

Add githubWorkflowCheck to prePR

---

.github/workflows/ci.yml
build.sbt

Setup codecov

---

core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala

a few optimizations more

---

core/shared/src/main/scala/cats/parse/Rfc5234.scala
core/shared/src/test/scala/cats/parse/Rfc5234Test.scala

RFC5234 common rules

---

core/shared/src/main/scala/cats/parse/Parser.scala

close #72 
This is a matter of optimizations creating redundant failure offsets. Originally I removed those, but then I took that out to make things simpler.
Now I go back to removing a naked Fail Expectation which is at an offset that other non Fail messages have already failed at. This adds nothing to the user.
We have to have a naked Fail expectation to have the empty value for the MonoidK, but users will probably prefer failWith which allows them to set a custom error message, which is not normalized away.
cc @non

Fix issue 72

---

core/shared/src/main/scala/cats/parse/Parser.scala

Avoid oneOf reverse on List

---

core/shared/src/main/scala/cats/parse/SemVer.scala
core/shared/src/test/scala/cats/parse/SemVerTest.scala

A potential part of #9 
I wanted to get myself familiar with parser combinators in general and played with this lib over the weekend.
I tried to implement a SemVer parser as an exercise by following [the BNF grammar of SemVer](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) and wanted to share for both feedback and contribution if you'd like to incorporate it.
Thanks in advance.

Add SemVer Parser

---

build.sbt
project/Dependencies.scala

Just putting all deps in one place

Cleanup deps

---

build.sbt
codecov.yml

Ignore bench from codecov

---

build.sbt

@regadas This is working for me after all - not sure why it didn't work initially, perhaps I lost track while trying different things.

Simplify bench project Scala version exclusions

---

core/shared/src/main/scala/cats/parse/Parser.scala

I noticed some flatMaps in call stacks that should not have them so I was implementing more applicative methods in terms of product.
I think ap2 should also be looked at, but the order is a bit strange, so I punted for now. The flatMap based implementations parse the values in different orders than I would expect, so I think that function is a bit dangerous for a Parser.

Override productEval methods in FlatMap

---

.github/workflows/ci.yml
build.sbt
project/Dependencies.scala

Update to scala 3.0.0-M3, cats, and munit

---

core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/main/scala/cats/parse/RadixNode.scala
core/shared/src/test/scala/cats/parse/BitSetTest.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala
core/shared/src/test/scala/cats/parse/RadixNodeTest.scala

The main idea here is to merge adjacent Str and StringIn nodes in order to take advantage of the log vs linear complexity of matching that the RadixNode offers
cc @satabin

Merge adjacent StringIn nodes in oneOf

---

core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/main/scala/cats/parse/Rfc5234.scala
core/shared/src/main/scala/cats/parse/SemVer.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala

Adds a synonym for orElse, which is common in parsing libraries.

Add | operator

---

core/shared/src/main/scala/cats/parse/Parser.scala

I think we can simplify the type signature a little bit wdyt?

Remove `as` Parser type param

---

core/shared/src/main/scala/cats/parse/Accumulator.scala
core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/test/scala/cats/parse/AccumulatorTest.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala
core/shared/src/test/scala/cats/parse/RepParserConstructionTest.scala

Add max parameter for rep(0) and repAs(0).
Fixes #97

allow for max in rep

---

core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala

Cleanup accumulated errors

---

core/shared/src/main/scala/cats/parse/Parser.scala

I think snapshot publishing is not happy because of this.

Fix scaladoc

---

bench/src/main/scala/cats/parse/bench/self.scala
core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/main/scala/cats/parse/SemVer.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala
docs/src/index.md

part of #111 follow on to #141
cc @martijnhoekstra

More repSep related clean ups

---

core/shared/src/test/scala/cats/parse/ParserTest.scala

I was just going through the tests and noticed these.

Fix a few more tests not running

---

core/shared/src/main/scala/cats/parse/Parser.scala

:art: be consistent on overrides

Add missing overrides

---

bench/src/main/scala/cats/parse/bench/self.scala
core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/test/scala/cats/parse/ParserTest.scala
docs/src/index.md

Add a helper method to make it cleaner to write recursive parsers.
cc @regadas @martijnhoekstra

Add a recursive method

---

core/shared/src/main/scala/cats/parse/Parser.scala

This adds some comments related to #184 and #188

Add some comments to improve documentation

---

core/shared/src/main/scala/cats/parse/Parser.scala

Cache hashCode

---

.github/workflows/ci.yml
build.sbt
core/shared/src/test/scala/cats/parse/ParserTest.scala
project/Dependencies.scala

Update to Scala 3.0.0-RC3

---

bench/src/main/scala/cats/parse/bench/self.scala
docs/src/index.md

Just wanted to update to see how much @rossabaker 's code in #280 helped the benchmarks (and fix an issue with the json parsing).

Fix json code, run bench

---

.scalafmt.conf

Update scalafmt to 3.1.0

---

.github/workflows/ci.yml
build.sbt

Add scaladoc generation to CI build

---

core/js/src/main/scala/cats/parse/BitSet.scala
core/jvm/src/main/scala/cats/parse/BitSet.scala
core/shared/src/main/scala/cats/parse/Parser.scala
core/shared/src/test/scala/cats/parse/BitSetTest.scala

Follow up to https://github.com/typelevel/cats-parse/pull/291/files#r740001716
Might not be a huge deal but it doesn't hurt.

Add BitSet union iterator

---

.github/workflows/ci.yml
bench/src/main/scala/cats/parse/bench/fastparse.scala
build.sbt

Update scala to 2.13.7

---

build.sbt

Add scala3 mima rules for RadixNode

---

docs/index.md

Update version strings in index.md

---

docs/index.md

close #601 
cc @hamnis @carueda

Bump docs version to 1.0.0
